#!/bin/bash

FPATH="$1"

COMMAND=/usr/bin/file
FNAME=$(basename "$FPATH")

RET=$($COMMAND -bi "$FPATH")
test $? -ne 0 && exit $?

MIME=$(echo $RET | sed -e 's/\([^;]\+\)\(;\s*.*\)\?/\1/')
OPT=$(echo $RET | sed -e 's/\([^;]\+\)\(;\s*.*\)\?/\2/')

# for PDB (Protein Data Bank)
#NEW_MIME="chemical/x-pdb"
NEW_MIME="model/x-pdb"
test "$MIME" = "chemical/x-pdb" && MIME="text/plain"
if test "$MIME" = "text/plain"; then
  HEAD=$(head -c 6 "$FPATH")
  if test "$HEAD" == "HEADER"; then
    SECTIONS="HEADER OBSLTE TITLE SPLT CAVEAT COMPND SOURCE KEYWDS EXPDTA NUMMDL MDLTYP AUTHOR REVDAT SPRSDE JRNL REMARK DBREF DBREF1 DBREF2 SEQADV SEQRES MODRES HET FORMUL HETNAM HETSYN HELIX SHEET SSBOND LINK CISPEP SITE SCALE1 SCALE2 SCALE3 CRYST1 MTRIX1 MTRIX2 MTRIX3 ORIGX1 ORIGX2 ORIGX3 MODEL ATOM ANISOU TER HETATM ENDMDL CONECT MASTER END"
    FSECTIONS=$(awk '{print $1}' "$FPATH" | cut -c 1-6 | sort | uniq)
    IS_PDB=1
    for i in $FSECTIONS; do
      SECT_OK=0
      for j in $SECTIONS; do
        test "$i" = "$j" && SECT_OK=1 && break
      done
      test $SECT_OK -eq 0 && IS_PDB=0 && break
    done
    test $IS_PDB -ne 0 && RET="$NEW_MIME$OPT"
  fi
fi

echo $RET
